### ISSUE TITLE
Adding `1.` before text to convert to numbered list is instead adding link to first word

### ISSUE THREAD

**Issue by devcer** [remirror/remirror#1585]
### Summary

Converting node to list item is incorrectly adding link on first word before actually converting to list item

### Steps to reproduce

1. Open https://remirror.vercel.app/?path=/story/editors-markdown--basic
2. Add text to the document
3. Now go to the beginning of any line to add `1.` to convert the line into a list item
4. The first word is converted to link before the whole node getting converted to list item

### Expected results

node should be converted to list item

### Actual results

First word is converted to link before converting to list item

### Possible Solution

When the node is converted to list item, it should remove the link on first word

### Screenshot(s)

https://user-images.githubusercontent.com/3799600/161754393-1bb94049-90fc-418c-a349-16163e3e45cb.mov

**Comment by labkey-alan** [comment]
We were running into this issue as well, the problem is that the default URL regex used by Remirror is too lenient in defining what a valid URL is. This is obviously not a super trivial problem (there are over 1300 TLDs), so we opted to modify the existing regex to restrict it to URLS that start with http://, https://, or www. The modifed Regex we use is:

```javascript
export const urlRegex = /(?:https\:\/\/|http\:\/\/|www\.)+(?:(?:[\da-z\u00A1-\uFFFF][\w\u00A1-\uFFFF-]{0,62})?[\da-z\u00A1-\uFFFF]\.)+[a-z\u00A1-\uFFFF]{2,}\.?(?::\d{2,5})?(?:[#/?]\S*)?/gi;
```
