### ISSUE TITLE
`text-color-extension` does not change the color of bullets/markets in a list. 

### ISSUE THREAD

**Issue by Anenth** [remirror/remirror#1792]
### Summary

When we select the entire list and change the color using `text-color-extension`, it only changes the color inside the list items and does not change the color of the bullet icons.

### Expected results

When the entire list is selected, it should also change the color of the bullets 

### Actual results

When the entire list is selected, only the text inside the list will change color

### Screenshot(s)

![PixelSnap 2022-07-19 at 08 29 07](https://user-images.githubusercontent.com/1499218/179654888-e57c1d94-1a96-4c81-bc5b-a3f482788b3d.jpg)

**Comment by ocavue** [comment]
`TextColorExtension` indeed doesn't change the color of bullets, because bullets are not part of *text*. These bullets are a part of the list item blocks, and are controlled by the [list-style-type](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type) CSS rule. 

There are some ways to color a bullet, for example, we can add a new `color` attribute to the list item node in `ListItemExtension`. However, I'm not sure how to design UX, since a bullet can not be selected (again, because the bullet is not text).

**Comment by ocavue** [comment]
Maybe you didn't define the new `code` attribute for `ListItemExtension`. This doc should help a bit: https://remirror.io/docs/concepts/extra-attributes

**Comment by Anenth** [comment]
It did work but, It's adding the attribute only to 1st item(li) on the list. I was expecting it will add on `ol`

These are the code snippets.
```
 new ListItemExtension({
          extraAttributes: {
            style: {
              default: 'color: #000000',
              parseDOM: (domNode) => domNode.getAttribute('style'),
            },
          },
        }),
```

```
@command()
  setListMarkerColor(color: string): CommandFunction {
    return ({ tr, dispatch }) => {
      const list = findParentNodeOfType({
        types: ['orderedList', 'bulletList'],
        selection: tr.selection,
      });
      if (list) {
        dispatch?.(
          tr.setNodeMarkup(list.start, undefined, {
            ...list.node.attrs,
            color,
            'marker-color': color,
            style: `color: ${color}`,
          }),
        );
        return true;
      }
      return false;
    };
```

![PixelSnap 2022-07-20 at 10 35 05](https://user-images.githubusercontent.com/1499218/179901077-04c456fb-0df6-4580-917c-48891c9f4fb9.jpg)

**Comment by ocavue** [comment]
You current code is adding color to the first list item (`<li>` HTML element) in the list. If you want to set all list items in a list with the same bullet color, you should add this attribute to list node (`OrderedListExtension`, `<ol>`) instead of list items, and then maybe use some CSS magic to set the bullet color for all list items (`<li>`) under this list (`<uo>`). If you want to be able to set different color for different items in a list, then you should call `setNodeMarkup` in a for loop and set the color for every item. 

This post from ProseMirror could help: https://prosemirror.net/docs/guide/

**Comment by Anenth** [comment]
@ocavue thanks alot, After adding the options in `OrderedListExtension` and changing the `list.start` to `list.pos` it worked.

### Here is a complete solution on how to add marker color.
#### 1. Add attribute to the `OrderedListExtension` 
- I am adding a CSS variable to target only the marker
- You can add the same options to `BulletListExtension`, if you want to change the bullet color also
```js
	new OrderedListExtension({
          extraAttributes: {
            style: {
              default: '--marker-color: #000000',
              parseDOM: (domNode) => domNode.getAttribute('style'),
            },
          },
        }),
```

#### 2. Create a PlainExtention
```js
import { command, CommandFunction, extension, findParentNodeOfType, PlainExtension } from '@remirror/core';

@extension({})
export class ListMarkerColorExtension extends PlainExtension {
  get name() {
    return 'ListMarkerColor' as const;
  }

  @command()
  setListMarkerColor(color: string): CommandFunction {
    return ({ tr, dispatch }) => {
      const list = findParentNodeOfType({
        types: ['orderedList', 'bulletList'],
        selection: tr.selection,
      });
      if (list && dispatch) {
         dispatch(
          tr.setNodeMarkup(list.pos, undefined, {
            style: `--marker-color: ${color}`,
          }),
        );
        return true;
      }
      return false;
    };
  }
}
```

#### 3. Call `setListMarkerColor` when the user change the color
#### 4. Add the new CSS style 
```css
.rich-text__html-value li::marker {
  color: var(--marker-color);
}
```
