### ISSUE TITLE
Resized table columns is not reflected when editable is set to false

### ISSUE THREAD

**Issue by ngamanda** [remirror/remirror#1937]
### Summary

We're using the Remirror editor to edit and display the content. After resizing the table columns and setting the editor mode to false, the table columns are back to equal width instead of the resized width.

### Steps to reproduce

Create an editor, resize the column, save the changes and display the content when the editor has the `editable` prop set to false.

### Expected results

Columns width should show the width set by the user

### Actual results

Columns width reverts back to equal width

### Possible Solution

N.A

### Screenshot(s)

![Table issue](https://user-images.githubusercontent.com/10681923/201058141-47987de3-a1d9-4758-825c-a374b542fcd7.gif)

**Comment by dgaletto** [comment]
hey @ngamanda 

I have been working on a solution for this.
The solution that worked best for us was to add the width to the table, since we use the resulting html for different outputs (email, pdf, etc).
 Here is my progress https://github.com/remirror/remirror/commit/a5e542ee09a645139b00fed2f2ea0b2afa0d211f

![resizing-table](https://user-images.githubusercontent.com/3117239/203552937-688c8518-2580-4dad-8cc6-1f7462e09d36.gif)
There is a small delay in the view but it is because it is saving on the server. It is not related to Remirror

the bug that I still have to fix is when the table is resized to be smaller.
![resizing-table-bug](https://user-images.githubusercontent.com/3117239/203553903-f178457f-8bae-4387-ace4-01cb8c5ba8f0.gif)


Oh and in case the initial content includes a table and its columns are in % I decided to omit this attribute because I did not know how to handle it, since Prosemirror-Table works with PX.

What are your thoughts? @ocavue

**Comment by ngamanda** [comment]
Hi @dgaletto, this looks great and exactly what I was looking for. Right now my intermediary solution was to set it as `enabled` initially to trigger the loading of the extensions, and then disabling them with a `SetTimeout` after. 

This approach is way better than what I came up with.

**Comment by whawker** [comment]
This should be resolved by https://github.com/remirror/remirror/pull/1948
