### ISSUE TITLE
Why there so many ts errors？

### ISSUE THREAD

**Issue by zhoudaxia2016** [remirror/remirror#2251]
### Summary

I clone the repo and want to build storybook local,
but run `yarn storybook` give me so many ts errors. 

### Steps to reproduce
```bash
git clone https://github.com/chanzuckerberg/czi-prosemirror.git
cd czi-prosemirror
pnpm i
pnpm storybook # or other npm scripts
```
### Expected results

No errors

### Actual results
![image](https://github.com/remirror/remirror/assets/24446852/431ddd04-4ceb-4f78-9fdb-c8345d732ecb)

When I add   `"noImplicitAny": false` to fix the errors, I get other more ts errors...

**Comment by whawker** [comment]
This should be resolved now if you use the latest version. This was due to the upstream ProseMirror model package changing the definition of `ParseRule` to be a union

If you see this in a custom extension, you can use 

`satifies TagParseRule` or `satisfies StyleParseRule` as appropriate 

See here https://github.com/remirror/remirror/blob/main/packages/remirror__extension-text-case/src/text-case-extension.ts#L52-L79
