### ISSUE TITLE
How to get data from Wysiwyg Editor?

### ISSUE THREAD

**Issue by arpitchaudhari** [remirror/remirror#267]
I want to get data from editor so that I can save in the database.

`<WysiwygEditor onChange={(e)=>console.log(e)}/>`

I had tried this but not getting the data.

**Comment by ifiokjr** [comment]
There are two options 

https://github.com/remirror/remirror/blob/d1359ada00898e6f2092b1f9da33c2cb0f530c03/%40remirror/react/src/react-types.ts#L449-L459

- `getJSON()` - the json for the full state value including the current selection.
- `getObjectNode()` - the json for the editor content.


It's not well documented right now but that's being fixed in the upcoming version. 

```tsx
import {RemirrorEventListener} from '@remirror/react';
const MyEditor = () => {
  const onChange = ({ getObjectNode }: ) => {
  return <WysiwygEditor onChange={onChange} />
