### ISSUE TITLE
Render ReactNodeView instance into the element of toDOM

### ISSUE THREAD

**Issue by zhaoyao91** [remirror/remirror#271]
By the original NodeView logic, my dom/node will replace the original element from toDOM. But if I use the ReactNodeView, it will render the react component inside the element from toDOM.

see the related code here:

![image](https://user-images.githubusercontent.com/3808838/76519166-70005580-649b-11ea-8890-9c39fb905bd7.png)

![image](https://user-images.githubusercontent.com/3808838/76518622-662a2280-649a-11ea-8989-7dc8e52801be.png)

In my case, I have a custom extension for block image. the toDOM is required since we will get the html from the editor. I want to create a node view for it to provide a more functions to use, but the react-node-view just go inside the origin img tag, like this:

![image](https://user-images.githubusercontent.com/3808838/76519055-37607c00-649b-11ea-84b6-5fe1e31e2932.png)

So how to create a react node view to **REPLACE** the original element from toDOM instead of inside it?

## Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by zhaoyao91** [comment]
here is my related code
![image](https://user-images.githubusercontent.com/3808838/76519232-91f9d800-649b-11ea-996c-51d4412f1269.png)

**Comment by ifiokjr** [comment]
Good spot!

I'm open to a PR to fix it.

**Comment by ifiokjr** [comment]
Node views aren't great in `remirror` at the moment. Mainly because I'm actually not currently using any. The times I did there were some issues with mobile support so I just reverted to other solutions. 

However, I'm very impressed by [this repo](https://github.com/johnkueh/prosemirror-react-nodeviews) which has a great `NodeView` with `React` integration. I've reached out to the developer and will be borrowing some of the ideas to use here in `remirror`.

**Comment by ifiokjr** [comment]
Okay, I remember why it's like this. 

It's not possible not to have the nesting in `React` due to this issue https://github.com/facebook/react/issues/12227. Also, it's unlikely that any changes will be made in ProseMirror, which makes a lot of sense https://github.com/ProseMirror/prosemirror/issues/803

NodeViews have a `dom` node which is the top element. For paragraphs this would be the `p` tag and for text this is a `TEXT` node. NodeView's  also have a `contentDOM` property which is where any content from ProseMirror is injected.

The difficulty in integration is that the dom node and the content dom node of the `NodeView` are consumed synchronously by ProseMirror. However, react requires a ref to determine where the node has been mounted and this is done asynchronously. As a result it's not possible provide the `dom` node or `contentDOM` to ProseMirror while using react. 

The only way around this, is to create both the top level dom node and the content dom manually in the NodeView and provide a ref to the component which should be attached to the part of the tree where content should be rendered to. Once the React ref is available asynchronously the `contentDOM` can be appended to it.

I'm currently improving the API in the next branch and I'll update docs on how it should be used once done.

**Comment by tommoor** [comment]
Hey @ifiokjr do you have a snippet of how this should be achieved on `next` branch? I have `ReactComponentExtension` in `useManager` and my custom block which extends NodeExtension with a `ReactComponent` attribute, but it seems that method is never called :( 

```
  const manager = useManager([
    new ReactComponentExtension(),
    new LayersExtension({ useContent: false }),
  ])
```

**Comment by ifiokjr** [comment]
I'm closing this in favour of #479
