### ISSUE TITLE
Inject custom prop to remirror context

### ISSUE THREAD

**Issue by lanyusan** [remirror/remirror#291]
## Description

`useRemirrorContext` is very convenient. I need to pass some extra props for `useRemirrorConext` to capture, for example a GraphQL client instance.

Is there a way to do it now? If not, can I propose such a feature. For max flexibility, it should use a template type for user to define what to pass to the context.

Thanks in advance

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
This is an interesting suggestion. In the `next` version #251 of the codebase, I’ve sought to make the underlying core more extensible. So much so that, now, all core functionality is implemented with`builtin` extensions. 

However, I’m not sure I see the benefit in adding extra props to the context of the react provider. Could you shed more light on what it is you’re trying to achieve and how passing the extra props will make that possible?

**Comment by lanyusan** [comment]
My use case is that my extensions would need to access remote resources, through graphql. The graphql client could be passed down through extension options, but  since the client is a shared resource, it would be nice to put it in editor context. 

Generally speaking, context is a nice place for shared resources.

**Comment by ifiokjr** [comment]
What would you suggest the API should look like? Perhaps it's a change that can be added to the `next` version.

**Comment by lanyusan** [comment]
May be as a prop of ` <RemirrorManager extensions={extensions}>` , as  expanded to  ` <RemirrorManager extensions={extensions} externalContext={{gqlClient, credentials, ... }}`>

**Comment by ifiokjr** [comment]
Thinking about this again. It seems possible to just create your context provider that can also be used within the editor. Adding this to `useRemirror` would complicate the types unnecessarily.
