### ISSUE TITLE
Calling multiple commands only registers the last command

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#418]
## Description

**[Playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBItVr0mBgA3FH5ybEsycgBZVl5WTnDIij8lHAdxTEkZBX9lFVdzDwMMbysAIUxmfgBRAA9ccl5SFExeDKccxQDVcgamlraVACMq-mKvYyIACRwUAC823FZmSmJmcnrG5tb2kUzsl278vu3B3hUACznF3mXmAFpsdfIZfX0ENtICGoANABUagA5ADKAEkAPKg-AAXnwAG19PhkfheOQAO74SrVLYDXYACgAlLAkSi0ZjZtgFksVmsNridm0ifoALp6Xj6FQAKi5SK5+H+lxQpHwn1KaLuoppKGa+Fwl3I+HI-BQuHScUEcXYcswVWGrGwpBUCEuEkVqvwCgAjsQ6ORSAA6PkqD5fAggsArZg1FVq7CQGz2OFE2EAPkIpM+zR8+ESuEoutwjAY6FIljFnoEIpEcKiqR6RPZpIUuGI2Ha+NJyIAPCqgqGqyjayggoQHe24wnMEmU6QiSIVA32iia8NiLg1e02rZmCgEABrGHAEMw8PARsjjMax1qzicDbY-jM4cj5FbrMO65U273OnkY+n4RCIeP5Gjar4ABk+FNG-w1ZGcdJxfJsVDrEDCXZIQi14KNvnwD0vR9VUcAAdWwVh0HQcJYXwFc10jN0lX6RleFieJEmwXConIhJwnxP5AVBSFQUg95hzgmMghWYhyEsadLjiRIHFzFJjiYDRuEwPgj1OPE2loyjIPwFQVHwAARcgNkaOUhRFWc0XY5ESzLCtG2rfNlGTTAQjCbA-0zOjsCXOTSMU8IhD-bjmF4pdvN4zyTxRAShPIJcQt4RJApHECR2rRDmG9X10kHcyVEswIbNCcIIKgmC+iMAgwlEVh1ndT1EuQv10Mw7DsHZEAhCAA)**

To reproduce, please enter some text, select the text, then toggle the button on the page. You'll see that only the last command (command.horizontalRule) gets applied.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Wow, this is a bad bug to have. It's definitely **high priority**.

**Comment by ifiokjr** [comment]
So, it was in fact to do with the controlled editor. 

### Explanation

Commands use the current state stored on `view.state` to dispatch transactions and create a new state. In most editors this is fine since once dispatched the state is updated synchronously. With **controlled** editors there's delay between the `view.dispatch` and the state being updated. 

When attempting to synchronously run multiple commands in a controlled editor, each command operates on the current state, not the state as applied by the previous command. As a result, we find ourselves in a situation where the last command wins. i.e. the last state update before the controlled editor can apply the new state is the one that will be used. 

Since the playground is a controlled editor, that's what we can observe.

I created a [controlled editor test](https://github.com/remirror/remirror/blob/7477b9357368d62e201d05db4d9872954ae13c11/packages/%40remirror/react/src/components/__tests__/react-editor-controlled.spec.tsx#L368-L418) showing that this is actually expected behaviour. Making multiple state updates before the state has been updated will not work in a controlled editor.


### Chained Commands

The advised workaround is to use `chained` commands. 

```ts
const { chained } = useRemirror();

chained.toggleBold().toggleItalic().toggleUnderline().run();
```

Chained commands allow composing different commands together that have updated to use the ProseMirror `transaction`. This means that each command adds new steps and when the `.run()` is called all these steps are dispatched at the same time. 

Not all commands are chainable. 

**There are some that will never be chainable.** 

- `undo`
- `redo`

These only work with the synchronous` state updates and it probably doesn't make sense to use them as part of a chain. Calling them with `chained` will throw an error.

**There are some that still need to be made chainable**

In #422 I've converted most of the commands to be chainable. I've left out the `@remirror/preset-table` and `@remirror/preset-list` now since they require a bit more work to convert their commands to rely on transactions rather than state. 

All that is needed is to convert the commands being imported from `prosemirror-tables` and `prosemirror-schema-list` to use transactions rather than the state. 

You can see an example of one such conversion [here](https://github.com/remirror/remirror/blob/7477b9357368d62e201d05db4d9872954ae13c11/packages/%40remirror/core-utils/src/command-utils.ts#L128-L164).

### Summary

- Use `chained` commands where possible. 
- Commands that update the transaction can also be used since the same transaction is shared.
- Certain commands will never be chainable. If you are using TypeScript this will be obvious as they are non-callable.
- Work will be done to convert the `@remirror/preset-tables` library and `@remirror/preset-list` to use chainable commands.

Finally, I'll need to write some docs so that is a known limitation for users working with controlled editors.
