### ISSUE TITLE
onChange callback does not get updated in StrictMode

### ISSUE THREAD

**Issue by Bertg** [remirror/remirror#555]
### Summary

When remirror is rendering in ```StrictMode```, the ```onChange``` callback does not get updated. In other words, remirror seems to "hold on" to the first ```onChange``` value it receives.

### Steps to reproduce

Go to this sandbox: https://codesandbox.io/s/frosty-microservice-ztcj7?file=/src/index.tsx
Interact with the button & text editor for some time.

### Expected results

We expect the debug values for ```onChange``` to be up to date. Meaning ```htmlValue```, ```controlValue``` and ```value``` should be up to date with the values outputted by ```renderLoop```

### Actual results

The values of ```onChange``` are locked to their initial values.

### Additional context

* This only happens in ```StrictMode```. You can easily toggle ```StrictMode``` in the sandbox by changing a variable in the ```index.tsx``` file.
* This is verified in the .21 release.

### Possible Solution

No idea.

**Comment by ifiokjr** [comment]
Thanks for raising the issue. I'll take a look at it in the next few hours.

**Comment by ifiokjr** [comment]
[**codesandbox link**](https://codesandbox.io/s/reverent-sinoussi-g90um?file=/src/App.tsx)

@Bertg this has been fixed and released in `remirror@1.0.0-next.23`. It also affected the uncontrolled editor in the same way as well. The reason for the issue was that `dispatchTransaction`, which is how the ProseMirror `EditorView` notifies the codebase of state changes, was not being updated when a new `EditorWrapper` was created. In strict mode the issue meant that all state updates were being fed to a stale copy of the `EditorWrapper` hence the reason for the `onChange` callbacks never being updated. 

As a result of my finding I've created #559 which should help prevent errors like this happening again, and when they do, make them easier to isolate and fix.

![2020-08-18 07 17 33](https://user-images.githubusercontent.com/1160934/90477332-1fb0b200-e123-11ea-8ac1-8f18b8d54e25.gif)
