### ISSUE TITLE
Preserve text selection when editor loses focus (fake selection)

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#601]
The editor should give the illusion that the current selection stays even when the editor lost focus. This should only happen for specific actions that keep the user in the mindset of the current selection. 

### Example use case

The user selects a piece of text and pressed the [link] menu button. When the "link" dialog opens, the editor will loose the focus and therefore also the text selection. This means that the user won't see any longer which text will be converted into a link.
![image](https://user-images.githubusercontent.com/9339055/91550247-8f474e00-e928-11ea-835e-1e5f83097480.png)

### Solution idea

Atlassian seems to solves this be adding a fake-text-selection decoration at the place of the former selection:
![image](https://user-images.githubusercontent.com/9339055/91550220-822a5f00-e928-11ea-8dee-655764308a4b.png)

---

This issue has been initially raised and discussed on [Discord](https://discord.com/channels/726035064831344711/726035065338986528/748847321416204403)

**Comment by ifiokjr** [comment]
Yeah, this would actually be a great addition 🙌 

I think this should be added as one of the BuiltinPreset's.

https://github.com/remirror/remirror/blob/1d9492bd6efb29bb118514c8d7010c8658217c98/packages/%40remirror/core/src/builtins/builtin-preset.ts#L82-L95

For now, let's add the functionality requested but eventually, I'd like to generalize. 

For example, I've wanted to add want to add a focused decoration to any currently focused node. The problem is that this functionality is too small to create by itself as a new extension. My thinking is that perhaps we should generalize the process of adding decorations. 

It would allow adding handlers, which are checked on each change in the document so see what can be added automatically be run to generate decorations when the criteria are met.

I'll create a new issue to hopefully expand on the extra functionality idea.

**Comment by ankon** [comment]
@ifiokjr I wanted to look into this issue this week.

**Comment by ifiokjr** [comment]
@ankon sounds great! Let me know if you need any guidance either via discord, or directly on this issue.

**Comment by ankon** [comment]
https://github.com/remirror/remirror/pull/616 should provide this improvement, I'm just not sure where to put documentation and who exactly has to do the changeset thing.
