### ISSUE TITLE
next.35 breaks TablePreset

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#677]
### Summary

I upgraded to next.35. Calling `commands` (like `commands.bold`) cause a fatal TypeError if the editor contains `TablePreset`.

### Steps to reproduce

Minimal reproduction case: https://codesandbox.io/s/weathered-dream-pibtz

Downgrading to next.34 makes the reproduction case work.

### Expected results

No error

### Actual results

`TypeError: Cannot read property 'fixTables' of undefined`

![image](https://user-images.githubusercontent.com/9339055/93026210-a5316000-f604-11ea-91da-3f3e7e6eb9e9.png)

**Comment by ifiokjr** [comment]
Thanks for flagging. I was wondering why none of the tests had caught this, since there's quite a few tests for the `TablePreset`. Also, why could it not be replicated in the playground?

First, the tests use the `DomFramework` which actually wasn't passing the transaction through to the `onStateUpdate` method. As a result no tests failed. I've updated this as part of the PR and tests fail as expected (before the fix).

Second, the playground is currently a controlled editor where the state is fully controlled and transactions are not passed to the `onStateUpdate`. Since the bug was in a transaction method it couldn't be replicated there either.

**Comment by ronnyroeller** [comment]
Thanks for the quick fix, @ifiokjr ! `next.36` works fine.
