### ISSUE TITLE
AutoLinkExtension & LinkExtension duplicating link tags 

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#682]
### Summary

[Playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBIgEFiuJgAMii8ANYAogAeuOS8pCiYvA7imJIyCrT0OCrkMXEJSSqsAZgAtMyhYR4GGN5WIeHRsfGJySKp6S6K2ap5LYW8KpXhNV7GRNRZyowMAG4o-OTYlmTkALKsvKycy6sUU0o4++SMmAm4bcspThk9yiqu5jX6CEmkBBEAGgAqEQByAGUAJIAeSB+AAvPgABQASihAD58ABtXjkADu+H8gUakXyrSS8Ms6KxeOaBTa8IAunpePoVAAqRn6fCM-A-AAWKFI+DedXRvAIbyFrFCvNwnPI+HI-BQgWw+C2gi27HwgUwzAARqxsKQVAhORJpfL8AoAI7EOjkUgAOlZjJUr3eBEBYFYzGYETlCsgNns0PhSMIrL5Lqsu1wlEwmFws0w6F5Imha0OvXhdNDClwxGwyRhofw+AAPHK5ojC0WS2XCLa65Ho7H44n4SIVBXklWi8X1nFiPh25Xiyoyx2i3C6UJM7wRR98G6PV6fThbElcGL0YrAwjIcjgKHZwR+pSkpttrstyQKGedssYd8-kCwUCJ-oD+GiHMPcRyJYkrZOS2XYHBTA57iYDRuEwPh+BhY9CV4G8LwnAcVHwAARchmHIWJ1W5XkRnIN9O2zXN8yHNMZnmRZlkrIt3XPZZIWAeDBiQ5YhDo-Av2YH9mJ4n9OM7Lt-0A3hdmY0SgPIISuzHLsSwXT1vXlHAB3k7sVEophqKWbB5NfXgp2IvIjAIJZRBKZhXXdZTl2wVdRVCZZp1EPhzDafBe14Ygg33YTUI5KUr2lLALiuRVORjMIlU9TAMV5UQ1NwbAzDCUJODw6UEFzBQhXwChsI8pJ8FCLKZXs+0AsPQgtVjQIwEsbDRAsM1yFEZMQrOcKkjvAByLViC1LVsL6wzKxqoh+QY-hSEsNwUDmaVOtTcDsBhIgSkCABVdB+FYWI-RSn9hHGgLSLzWEuNLRa2tEZiFA6grcHYbDmKIOrcAapr2tasL5TaP0+tYLVSE1AJyD6ywhCEDSFOLQavqSLiRN4WxKgQMJmKDXcwzAGa7WIPaDvIPENqNdq-RkXAMXlWJsFtfkZCEOFZIUos4fZn4yPVTB8BGaoAq7YdEcCXhOZLEdFrhwyiyEEAhCAA)

When `AutoLinkExtension` and `LinkExtension` are used together, they should respect the existence of each other.

### Steps to reproduce

1. In the playground, type `test.com`
2. Highlight the text and click the `Turn to link` button
3. Notice nested `a` tags 

### Expected results

We'd expect the current `a` tag created from the `AutoLinkExtension` to update with what `commands.updateLink` passes.

### Screenshot(s)

<img width="1773" alt="Screen Shot 2020-09-14 at 11 24 16 AM" src="https://user-images.githubusercontent.com/12195101/93105474-1f053000-f67d-11ea-9495-fb86a52a8739.png">

**Comment by ifiokjr** [comment]
They shouldn't actually be used together any more. The `LinkExtension` with the options set to `{autoLink: true}` removes the need for the `AutoLinkExtension`. I've deprecated the import (TypeScript users), and will consider fully deprecating the package since it doesn't make sense to have two extensions replicating the same functionality.


However, there is a bug there in the `LinkExtension`. It's actually not possible to switch off the `autoLink` option. The option is ignored and doesn't actually change anything. I commented out a block and didn't undo my change before merging.

https://github.com/remirror/remirror/blob/0162606024f65269a20e5c0816214cc60f56209e/packages/%40remirror/extension-link/src/link-extension.ts#L233-L235

If you're able to, I'd welcome a PR fixing it.
