### ISSUE TITLE
useRemirrorContext misses commands in production build

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#869]
### Summary

When using `useRemirrorContext/useCommands` in production-mode (webpack build), the `commands` field is undefined:
![image](https://user-images.githubusercontent.com/9339055/108072226-e839a880-7066-11eb-847a-4f07052baf14.png)

@ifiokjr had pointed out that the `view` being `undefined` likely causes the `commands` to be undefined.

See also discussion on Discord: https://discord.com/channels/726035064831344711/745695521305526302/811186933388148757

### Steps to reproduce

I'm setting up an editor context via:
```
const manager = createCoreManager([...]):
...
<Remirror manager={manager} />
```

Next, I'm accessing the commands via (note: the same happens for `useCommands`):
```
const { commands } = useRemirrorContext();
```

Running this development mode, the commands are set. In production mode (i.e. webpack build), the commands are `defined`.

**Comment by ifiokjr** [comment]
This was fixed by using `useRemirror` to pass in the manager rather than directly creating a manager with `createCoreManager`. 

I'll add a note to the docs, that to prevent issues when re-rendering it's advisable to use the `useRemirror` hook even if you are creating a manager outside the editor component.

Thanks for raising 👍
