### ISSUE TITLE
Copying a React table adds an additional column + row

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#995]
### Summary

Copying a React table adds an additional column

### Steps to reproduce

1. Open storybook for React table https://remirror.vercel.app/?path=/story/react-tables-extension--table
2. Add a 3x3 table
3. Adds content in table cells (without this, only a new column is created - no new row)
4. Copy & paste the table
=> The pasted table is 4x4

https://user-images.githubusercontent.com/9339055/124762383-20b52280-df33-11eb-99ec-6a3738372ac7.mov

### Expected results

Copied table has the same number of columns and rows like original table.

### Actual results

A column is added to the left and row added on top (if the table is empty: only the column is added).

**Comment by whawker** [comment]
It seems the `parseDOM` rules are parsing the controller cells as actual cells.

So a table of the shape below, where `[ ]` denotes a controller cell

```
[th] [th] [th] [th]
[th]  td   td   td
[th]  td   td   td
[th]  td   td   td
```

Becomes

```
[th] [th] [th] [th] [th]
[th]  th   th   th   th
[th]  th   td   td   td
[th]  th   td   td   td
[th]  th   td   td   td
```

**Comment by ocavue** [comment]
I think the biggest issue behind extension-react-tables is `tableControllerCell`. It's just an HTML structure that listens to some mouse events. It also doesn't contain any information from users' input. It's a bad idea to store `tableControllerCell` as a node in the schema, which causes many issues including this one. 

I found that `rich-markdown-editor` implement this kind of feature with ProseMirror decoration ([their code](https://github.com/outline/rich-markdown-editor/blob/2f179e746f9b68514ff6d43e1375cc2ada75f6b4/src/nodes/TableHeadCell.ts#L49)). I created a prototype by using their method at #1318 and you can see a live demo [here](https://pr1318-remirror-ocavue.vercel.app/?path=/story/extensions-react-table--basic). By using Decoration and removing `tableControllerCell` from the schema, it doesn't have the copy-paste issue anymore. 

https://user-images.githubusercontent.com/24715727/137234258-1925c12f-72aa-41bc-82e1-7c3c24a198f4.mov

While this seems to be a workable solution, it's a big breaking-change for extension-react-tables since it needs to remove a node type from the schema and it requires node migration from the user side. 

Any idea about this solution? Do you think it's the right direction?

**Comment by JokerDang** [comment]
Hi @ocavue, @ronnyroeller and @whawker. Could you share about release plan for this bug? I met bug from my task related to it!
